"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.createComment = exports.updateTicket = exports.getTickets = exports.getTicket = exports.apiToken = void 0;
var core_1 = require("./core");
Object.defineProperty(exports, "apiToken", { enumerable: true, get: function () { return core_1.apiToken; } });
var tickets_1 = require("./modules/tickets");
Object.defineProperty(exports, "getTicket", { enumerable: true, get: function () { return tickets_1.getTicket; } });
Object.defineProperty(exports, "getTickets", { enumerable: true, get: function () { return tickets_1.getTickets; } });
Object.defineProperty(exports, "updateTicket", { enumerable: true, get: function () { return tickets_1.updateTicket; } });
Object.defineProperty(exports, "createComment", { enumerable: true, get: function () { return tickets_1.createComment; } });
